---
kind: pipeline
type: docker
name: test

workspace:
  path: /app

steps:
  - name: waiton cache
   image: python:3.9-slim
    commands:
      - pip install --upgrade pip cookiecutter
      - rm -rf /project/*
      - cookiecutter --no-input -f ./ -o /project project_name="testing project"
      - lscpu
